services:
  api:
    build: .
    tty: true
    ports:
      - '8000:8000'
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests
    depends_on:
      - database

  database:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
