"""add qtd column

Revision ID: 9a1a97fc052d
Revises: 1eca14145d85
Create Date: 2023-03-26 18:39:06.527965

"""


# revision identifiers, used by Alembic.
revision = '9a1a97fc052d'
down_revision = '1eca14145d85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
