"""teste

Revision ID: a988b6c1a91e
Revises: 271dc149ed01
Create Date: 2023-04-14 17:53:52.651571

"""


# revision identifiers, used by Alembic.
revision = "a988b6c1a91e"
down_revision = "271dc149ed01"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
